# Generated by Django 2.2.24 on 2021-12-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='pub_date',
        ),
    ]
